services:
  - type: web
    name: ws-flask
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: super_segura_123456
