services:
  - type: web
    name: ws-flask
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: super_segura_123456
      - key: PYTHON_VERSION
        value: 3.12.3
